//
//  RoomPickerInteractor.swift
//  LuckyTrip
//
//  Created Ali Omari on 4/13/19.
//  Copyright © 2019 Ali Omari. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class RoomPickerInteractor: RoomPickerInteractorProtocol {

    weak var presenter: RoomPickerPresenterProtocol?
    let searchService = SearchService()
    
    //AO getting data logic must be added to interactor
    func getRooms() {
        //AO if internet available get from remote
        //if isConnected{}
        searchService.search(success: {[weak self] (rooms) in
            self?.presenter?.roomsLoaded(rooms: rooms)
        }) { (error) in
            //AO get from database
            self.presenter?.roomsLoadingFailed(error: error.localizedDescription)
        }
        
        //AO get from database
        /*else {
            self?.presenter?.roomsLoaded(rooms: //get from database])
         }*/
    }
}
