//
//  RoomPickerRouter.swift
//  LuckyTrip
//
//  Created Ali Omari on 4/13/19.
//  Copyright © 2019 Ali Omari. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class RoomPickerRouter: RoomPickerWireframeProtocol {
    
    weak var viewController: UIViewController?
    
    static func createModule() -> UIViewController {
        let view = R.storyboard.main.roomPickerViewController()!
        let interactor = RoomPickerInteractor()
        let router = RoomPickerRouter()
        let presenter = RoomPickerPresenter(interface: view, interactor: interactor, router: router)
        
        view.presenter = presenter
        interactor.presenter = presenter
        router.viewController = view
        
        return view
    }
    
    func dismissViewController() {
        viewController?.dismiss(animated: true, completion: nil)
    }
}
