//
//  RoomPickerInteractor.swift
//  LuckyTrip
//
//  Created Ali Omari on 4/13/19.
//  Copyright © 2019 Ali Omari. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class RoomPickerInteractor: RoomPickerInteractorProtocol {

    weak var presenter: RoomPickerPresenterProtocol?
    let searchService = SearchService()
    
    func getRooms() {
        searchService.search(success: {[weak self] (rooms) in
            self?.presenter?.roomsLoaded(rooms: rooms)
        }) { (error) in
            self.presenter?.roomsLoadingFailed(error: error.localizedDescription)
        }
    }
}
