//
//  RoomPickerProtocols.swift
//  LuckyTrip
//
//  Created Ali Omari on 4/13/19.
//  Copyright © 2019 Ali Omari. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import Foundation

//MARK: Wireframe -
protocol RoomPickerWireframeProtocol: class {
    func dismissViewController()
}
//MARK: Presenter -
protocol RoomPickerPresenterProtocol: BasePresenterProtocol {
    func dismissButtonDidPressed()
    func roomsLoaded(rooms:[Room]?)
    func roomsLoadingFailed(error:String)
    
    var rooms:[Room]? { get set }
}

//MARK: Interactor -
protocol RoomPickerInteractorProtocol: class {
    
    var presenter: RoomPickerPresenterProtocol?  { get set }
    func getRooms()
}

//MARK: View -
protocol RoomPickerViewProtocol: BaseViewProtocol {
    
    var presenter: RoomPickerPresenterProtocol?  { get set }
    func populateRooms()
}
