//
//  MainProtocols.swift
//  LuckyTrip
//
//  Created Ali Omari on 4/13/19.
//  Copyright © 2019 Ali Omari. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import Foundation

//MARK: Wireframe -
protocol MainWireframeProtocol: class {
    func goToRoomPickerViewController()
}
//MARK: Presenter -
protocol MainPresenterProtocol: class {
    func browseButtonDidPressed()
}

//MARK: Interactor -
protocol MainInteractorProtocol: class {
    
    var presenter: MainPresenterProtocol?  { get set }
}

//MARK: View -
protocol MainViewProtocol: class {
    
    var presenter: MainPresenterProtocol?  { get set }
}
