//
//  MainPresenter.swift
//  LuckyTrip
//
//  Created Ali Omari on 4/13/19.
//  Copyright © 2019 Ali Omari. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class MainPresenter: MainPresenterProtocol {
    
    weak private var view: MainViewProtocol?
    var interactor: MainInteractorProtocol?
    private let router: MainWireframeProtocol

    init(interface: MainViewProtocol, interactor: MainInteractorProtocol?, router: MainWireframeProtocol) {
        self.view = interface
        self.interactor = interactor
        self.router = router
    }

    func browseButtonDidPressed() {
        router.goToRoomPickerViewController()
    }
}
