//
//  MainInteractor.swift
//  LuckyTrip
//
//  Created Ali Omari on 4/13/19.
//  Copyright © 2019 Ali Omari. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class MainInteractor: MainInteractorProtocol {

    weak var presenter: MainPresenterProtocol?
}
